### ISSUE TITLE
Crashing Upon Startup

### ISSUE THREAD

**Issue by Daiko777** [bonepl/ChromaLeague#149] opened 2023-12-11 11:35 UTC
[cl.log.txt](https://github.com/bonepl/ChromaLeague/files/13634847/cl.log.txt)

Title says it all. When I start up, the loading screen will make my keyboard do a cool back-and-forth, however as soon as the game starts, it crashes and my keyboard goes black..

Currently using RazerBlackwidow v4 X and Razer Basalisk v3

**Comment by rominouuu** [comment] 2023-12-11 17:19
Same here !

**Comment by bonepl** [comment] 2023-12-11 18:57
What does the log say?

**Comment by rominouuu** [comment] 2023-12-11 20:14
[log.docx](https://github.com/bonepl/ChromaLeague/files/13640556/log.docx)

**Comment by bonepl** [comment] 2023-12-11 21:03
This is caused by https://github.com/bonepl/ChromaLeague/issues/146 . Needs to be addressed by riot.

**Comment by bonepl** [comment] 2023-12-15 23:12
Hi, check newest release [Chroma League 1.3.0](https://github.com/bonepl/ChromaLeague/releases/tag/v1.3.0) if it fixes the problem for you.

**Comment by Daiko777** [comment] 2023-12-16 09:10
1.3.0 Solved the issue for me-- Works well, haven't gotten any errors 

`03:01:15 [INFO] Started Chroma League, close this window to exit the application
03:01:15 [INFO] Detected Razer Chroma REST Api Version[core=3.34.02, device=3.34.02, version=3.34.02]
03:01:15 [INFO] Running ChromaLeague version 1.3.0
03:01:15 [INFO] Your ChromaLeague version is up to date!
03:05:59 [INFO] Game is loading
03:05:59 [INFO] Initialized ChromaRestSDK connection { sessionId: 52326 }
03:06:26 [INFO] {MYNAME} joined the game
03:19:02 [INFO] Razer Chroma SDK session 52326 ended with code 0
03:19:02 [INFO] Player left the game, waiting for another...
03:23:04 [INFO] Game is loading
03:23:05 [INFO] Initialized ChromaRestSDK connection { sessionId: 58025 }
03:23:25 [INFO] {MYNAME} joined the game
04:02:30 [INFO] Razer Chroma SDK session 58025 ended with code 0
04:02:30 [INFO] Player left the game, waiting for another...`

**Closed** 2023-12-16 09:42 UTC
Labels: duplicate
